name: myapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^3.15.1
  cloud_firestore: ^5.1.0
  firebase_storage: ^12.1.0 
  firebase_ai: ^2.2.1

  # UI & State Management
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  provider: ^6.0.5
  go_router: ^13.2.0
  image_picker: ^1.0.5

  # Image Classification (TFLite)
  tflite_flutter: ^0.11.0 # For running the model
  image: ^4.1.3 # For image processing
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/
