// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhORnK-Y4Sggmtvo_Pb7QhyXw9FRfVYkc',
    appId: '1:888198544533:web:1a9e395c4fbf38bbb0ef9c',
    messagingSenderId: '888198544533',
    projectId: 'cobaalpukat',
    authDomain: 'cobaalpukat.firebaseapp.com',
    storageBucket: 'cobaalpukat.firebasestorage.app',
    measurementId: 'G-R2ZH514V75',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgHXCLgBCDLUKGio7dML6pJpfWY2NplA8',
    appId: '1:888198544533:android:b308a534629e7515b0ef9c',
    messagingSenderId: '888198544533',
    projectId: 'cobaalpukat',
    storageBucket: 'cobaalpukat.firebasestorage.app',
  );

}